include:
  - ./unbound/compose.yaml
  - ./pihole/compose.yaml
  - ./caddy/compose.yaml

networks:
  dns:
    name: daggler-dns
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.53.0/24

  proxy:
    name: daggler-proxy
    driver: bridge

secrets:
  pihole_admin_password:
    file: /etc/daggler-home/secrets/pihole_admin_password