name: daggler-home

secrets:
  pihole_admin_password:
    file: /etc/daggler-home/secrets/pihole_admin_password

  grafana_admin_password:
    file: /etc/daggler-home/secrets/grafana_admin_password


networks:
  dns:
    name: daggler-dns
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.53.0/24

  monitoring:
    name: daggler-monitoring
    driver: bridge



volumes:
  prometheus_data:
    name: daggler-prometheus-data

  grafana_data:
    name: daggler-grafana-data



